/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
#define JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_

#include <jsonrpccpp/server.h>

class AbstractStubServer : public jsonrpc::AbstractServer<AbstractStubServer>
{
    public:
        AbstractStubServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<AbstractStubServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("sayHello", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "name",jsonrpc::JSON_STRING, NULL), &AbstractStubServer::sayHelloI);
            this->bindAndAddNotification(jsonrpc::Procedure("notifyServer", jsonrpc::PARAMS_BY_NAME,  NULL), &AbstractStubServer::notifyServerI);
            this->bindAndAddNotification(jsonrpc::Procedure("mergeMiningNote", jsonrpc::PARAMS_BY_NAME, "bits",jsonrpc::JSON_STRING,"hash",jsonrpc::JSON_STRING, NULL), &AbstractStubServer::mergeMiningNoteI);
            this->bindAndAddMethod(jsonrpc::Procedure("minedAuxpow", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_BOOLEAN, "auxpow",jsonrpc::JSON_ARRAY, NULL), &AbstractStubServer::minedAuxpowI);
        }

        inline virtual void sayHelloI(const Json::Value &request, Json::Value &response)
        {
            response = this->sayHello(request["name"].asString());
        }
        inline virtual void notifyServerI(const Json::Value &request)
        {
            (void)request;
            this->notifyServer();
        }
        inline virtual void mergeMiningNoteI(const Json::Value &request)
        {
            this->mergeMiningNote(request["bits"].asString(), request["hash"].asString());
        }
        inline virtual void minedAuxpowI(const Json::Value &request, Json::Value &response)
        {
            response = this->minedAuxpow(request["auxpow"]);
        }
        virtual std::string sayHello(const std::string& name) = 0;
        virtual void notifyServer() = 0;
        virtual void mergeMiningNote(const std::string& bits, const std::string& hash) = 0;
        virtual bool minedAuxpow(const Json::Value& auxpow) = 0;
};

#endif //JSONRPC_CPP_STUB_ABSTRACTSTUBSERVER_H_
